import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="menu">
          <Link href="/" className="menu-item">
            Home
          </Link>
          <Link href="/users" className="menu-item">
            Users
          </Link>
          <Link href="/foods" className="menu-item">
            Foods
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
